apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: microservices
type: Opaque
stringData:
  DB_USER: microapp
  DB_PASSWORD: 21f45a0505

  AUTH_DB_URL: jdbc:postgresql://my-rds.cy76a8owu7p0.us-east-1.rds.amazonaws.com:5432/auth_db?sslmode=require

  CATALOG_DB_DSN: postgres://microapp:21f45a0505@my-rds.cy76a8owu7p0.us-east-1.rds.amazonaws.com:5432/catalog_db?sslmode=require

  INVENTORY_DB_URL: postgres://microapp:21f45a0505@my-rds.cy76a8owu7p0.us-east-1.rds.amazonaws.com:5432/inventory_db?sslmode=require&uselibpqcompat=true

  ORDER_DB_DSN: dbname=order_db user=microapp password=21f45a0505 host=my-rds.cy76a8owu7p0.us-east-1.rds.amazonaws.com port=5432 sslmode=require

  PAYMENT_DB_URL: Host=my-rds.cy76a8owu7p0.us-east-1.rds.amazonaws.com;Port=5432;Database=payment_db;Username=microapp;Password=21f45a0505;SSL Mode=Require

  NOTIFICATION_DB_URL: postgres://microapp:21f45a0505@my-rds.cy76a8owu7p0.us-east-1.rds.amazonaws.com:5432/notification_db?sslmode=require

  ANALYTICS_DB_DSN: pgsql:host=my-rds.cy76a8owu7p0.us-east-1.rds.amazonaws.com;port=5432;dbname=analytics_db