apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: microservices

      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: auth-service

      containers:
        - name: auth-service
          image: 979700391724.dkr.ecr.us-east-1.amazonaws.com/microse-service-project:auth-service
          imagePullPolicy: Always

          ports:
            - containerPort: 8081
              protocol: TCP

          envFrom:
            - configMapRef:
                name: microservices-config
            - secretRef:
                name: database-secret

          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi

          startupProbe:
            tcpSocket:
              port: 8081
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: microservices
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
  - name: http  
    port: 8081
    targetPort: 8081
    protocol: TCP

  